Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

from ServicioTecnico import views, models
from rest_framework import routers, serializers, viewsets

from django.contrib.auth.models import User

#API Users propia de DJANGO - Problema:Encripta claves
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url','id', 'username', 'password']

class UserViewSet(viewsets.ModelViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()

#API Usuarios
class UsuarioSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = views.Usuario
        fields = ['url','user_id', 'username', 'password']

# ViewSets define the view behavior.
class UsuarioViewSet(viewsets.ModelViewSet):
    queryset = views.Usuario.objects.all()
    serializer_class = UsuarioSerializer

#API Equipo
class EquipoSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = models.Equipo
        fields = ['url','id', 'descripcion', 'marca', 'modelo']

# ViewSets define the view behavior.
class EquipoViewSet(viewsets.ModelViewSet):
    queryset = models.Equipo.objects.all()
    serializer_class = EquipoSerializer

#API RECIBO
class ReciboSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = models.Recibo
        fields = ['url','id', 'fechaEmision', 'valorTotal', 'tipo']

# ViewSets define the view behavior.
class ReciboViewSet(viewsets.ModelViewSet):
    queryset = models.Recibo.objects.all()
    serializer_class = ReciboSerializer


router = routers.DefaultRouter()
router.register(r'User', UserViewSet)
router.register(r'Usuario', UsuarioViewSet)
router.register(r'Equipo', EquipoViewSet)
router.register(r'Recibo', ReciboViewSet)

urlpatterns = [   
    #path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('', include('ServicioTecnico.urls')),
    #path('cliente/', cliente),
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('apiu/', include(router.urls)),
]

ServicioTecnico/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Usuario(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, primary_key=True)
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=30)
    def _str_(self) :
        return str(self.username)

class Cliente(models.Model):
    id = models.AutoField(primary_key = True)
    nombres = models.CharField(max_length = 50, verbose_name = 'Nombres')
    apellidos = models.CharField(max_length = 50, verbose_name = 'Apellidos')
    cedula = models.CharField(max_length = 10, verbose_name = 'Cedula')
    telefono = models.CharField(max_length = 9, verbose_name = 'Telefono')
    telefonoMovil = models.CharField(max_length = 10, verbose_name = 'TelefonoMovil')
    email = models.EmailField()
    direccion = models.CharField(max_length = 100, verbose_name = 'Direccion')

    def nombre_completo(self):
        return "{} {}".format(self.nombres, self.apellidos)
    
    def __str__(self):
        return self.nombre_completo()
    
    def __getitem__(self, key):
        return self.__dict__[key]

class Equipo(models.Model):
    id = models.AutoField(primary_key = True)
    descripcion = models.CharField(max_length = 100, verbose_name = 'Descripción')
    marca = models.CharField(max_length = 50, verbose_name = 'Marca')
    modelo = models.CharField(max_length = 50, verbose_name = 'Modelo')
    numSerie = models.CharField(max_length = 14, verbose_name = 'Numero de Serie')
    observaciones = models.CharField(max_length = 500, verbose_name = 'Observaciones')
    
    def nombre(self):
        return "{} {}".format(self.descripcion, self.marca)
    
    def __str__(self):
        return self.nombre()

class Servicio(models.Model):
    id = models.AutoField(primary_key = True)
    nombre = models.CharField(max_length = 100, verbose_name = 'Nombre')
    descripcion = models.CharField(max_length = 500, verbose_name = 'Descripción')
    valor = models.FloatField(verbose_name = 'Valor')

    def nombre_servicio(self):
        return "{} {}".format(self.nombre, self.valor)
    
    def __str__(self):
        return self.nombre_servicio()

opciones_roles = [
    [0, "Vendedor"],
    [1, "Tecnico"],
    [2, "admin2"]
]

class Empleado(models.Model):
    id = models.AutoField(primary_key = True)
    rol = models.IntegerField(choices=opciones_roles, verbose_name = 'Rol')
    nombres = models.CharField(max_length = 50, verbose_name = 'Nombres')
    apellidos = models.CharField(max_length = 50, verbose_name = 'Apellidos')
    cedula = models.CharField(max_length = 10, verbose_name = 'Cedula')
    email = models.EmailField()
    telefono = models.CharField(max_length = 10, verbose_name = 'Telefono')
    direccion = models.CharField(max_length = 100, verbose_name = 'Direccion')

    def nombre_completo(self):
        return "{} {} {}".format(self.rol, self.nombres, self.apellidos)
    
    def __str__(self):
        return self.nombre_completo()

class Diagnostico(models.Model):
    id = models.AutoField(primary_key = True)
    descripcion = models.CharField(max_length = 500, verbose_name = 'Descripción')
    defecto = models.CharField(max_length = 150, verbose_name = 'Defecto')
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    equipo = models.OneToOneField(Equipo, on_delete=models.CASCADE)

    def nombre_diagnostico(self):
        return "{} {} {}".format(self.equipo, self.defecto, self.descripcion)
    
    def __str__(self):
        return self.nombre_diagnostico()
    
    def __getitem__(self, key):
        return self.__dict__[key]

class Proveedor(models.Model):
    ruc = models.CharField(primary_key = True, max_length = 13)
    nombre = models.CharField(max_length = 50, verbose_name = 'Nombre')
    email = models.EmailField()
    direccion = models.CharField(max_length = 100, verbose_name = 'Direccion')

    def nombre_proveedor(self):
        return "{} {}".format(self.ruc, self.nombre)
    
    def __str__(self):
        return self.nombre_proveedor()

opciones_productos = [
    [0, "Garantia"],
    [1, "Sin Garantia"]
]

class Producto(models.Model):
    id = models.AutoField(primary_key = True)
    nroSerie = models.CharField(max_length = 13, verbose_name = 'Nro Serie')
    nombre = models.CharField(max_length = 50, verbose_name = 'Nombre')
    unidades = models.IntegerField(verbose_name = 'Unidades')
    precioCompra = models.FloatField(verbose_name = 'Precio Compra')
    precioVenta = models.FloatField(verbose_name = 'Precio Venta')
    marca = models.CharField(max_length = 50, verbose_name = 'Marca')
    modelo = models.CharField(max_length = 50, verbose_name = 'Modelo')
    tipo = models.IntegerField(choices=opciones_productos, verbose_name = 'Tipo')
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)

    def nombre_producto(self):
        return "{} {} {} {}".format(self.nroSerie, self.nombre, self.marca, self.tipo)
    
    def __str__(self):
        return self.nombre_producto()

class Pedido(models.Model):
    id = models.AutoField(primary_key = True)
    tiempoEntrega = models.CharField(max_length = 50, verbose_name = 'Tiempo Entrega')
    descripcion = models.CharField(max_length = 500, verbose_name = 'Descripción')
    productos = models.ForeignKey(Producto, on_delete=models.CASCADE)
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.tiempoEntrega

opciones_estadoRecibo = [
    [0, "Creado"],
    [1, "Progreso"],
    [3, "Facturado"]
]

opciones_tipo = [
    [0, "Venta"],
    [1, "Orden de Servicio"],
]

class Recibo(models.Model):
    id = models.AutoField(primary_key = True)
    fechaEmision = models.DateField(verbose_name = 'Fecha de Emisión')
    subTotalProductos = models.FloatField(verbose_name = 'Sub Total de Productos')
    valorTotal = models.FloatField(verbose_name = 'Valor Total')
    fechaCierre = models.DateField(verbose_name = 'Fecha de Cierre')
    estado = models.IntegerField(choices=opciones_estadoRecibo, verbose_name = 'Estado')
    subTotalServicios = models.FloatField(verbose_name = 'Sub Total Servicios')
    tipo = models.IntegerField(choices=opciones_tipo, verbose_name = 'Tipo')
    servicio = models.ManyToManyField(Servicio)
    diagnostico = models.OneToOneField(Diagnostico, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto)

    def nombre_recibo(self):
        return "{} {}".format(self.id, self.fechaEmision)
    
    def __str__(self):
        return self.nombre_recibo()
    
    def __getitem__(self, key):
        return self.__dict__[str, key]

templates/Producto/index.html
{% extends "base1.html" %}

{% block js %}

    <script>
        function eliminar_Producto(id) {
            console.log(id)
            Swal.fire({
                title: '¿Estás seguro?',
                text: 'La acción no se puede revertir',
                icon: 'question',
                showCancelButton: true,
                cancelButtonText: 'No, Cancelar',
                confirmButtonText: 'Sí, Eliminar',
                reverseButtons:true,
                confirmButtonColor: '#dc3545'
            })
            .then(function(result){
                if(result.isConfirmed) {
                    window.location.href = "eliminar/"+id+"/"
                }
            })
        }
    </script>

{% endblock %}

{% block tittle %} Lista de Productos {% endblock %}

{% block body %}
<div class="container py-4">
    <div class="card">
        <div class="card-header">
            <a name="" id="" class="btn btn-success" href="{% url 'registrarProducto' %}" role="button">Agregar nuevo Producto</a>
        </div>
        <div class="card-body">
            <h4 class="card-title">Productos</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nro. Serie</th>
                        <th>Nombre</th>
                        <th>Unidades</th>
                        <th>Precio Compra</th>
                        <th>Precio Venta</th>
                        <th>Marca</th>
                        <th>Modelo</th>
                        <th>Proveedor</th>
                        <th>Operaciones</th>
                    </tr>  
                </thead>
                <tbody>
                    {% for pro in entity %}
                    <tr>
                        <td>{{ pro.id }}</td>
                        <td>{{ pro.nroSerie }}</td>
                        <td>{{ pro.nombre }}</td>
                        <td>{{ pro.unidades }}</td>
                        <td>{{ pro.precioCompra }}</td>
                        <td>{{ pro.precioVenta }}</td>
                        <td>{{ pro.marca }}</td>
                        <td>{{ pro.modelo }}</td>
                        <td>{{ pro.proveedor }}</td>
                        <td>

                        {% if perms.ServicioTecnico.change_producto %}
                            <a class="btn btn-info" href="{% url 'modificarProducto' pro.id %}" role="button">Editar</a>
                        {% endif %}

                        {% if perms.ServicioTecnico.delete_producto %}
                            <a class="btn btn-danger" onclick="eliminar_Producto({{ pro.id }})" href="#" role="button">Eliminar</a>
                        {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div>
                {% include 'paginator.html' %}
            </div>
        </div>
        <div class="card-footer text-muted"></div>
        
    </div>
</div>
{% endblock %}

templates/Producto/modificarProducto.html
{% extends "base1.html" %}

{% load crispy_forms_tags %}

{% block body %}

<!Doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <div class="container py-4">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <b>Crear un Producto</b>
                </div>
                <div class="card-body" style="width: 70%;">
                    <h4 class="card-title">Datos del Producto</h4>
                    <!--{{request.user.is_authenticated}}-->
                    <form action="" class="" method="POST">
                                        
                        {% csrf_token %}
                        {{ form | crispy}}
                                        
                        <br>
                        <div class="d-flex justify-content.end">
                            <button type="submit" id="btnRegistrar" class="btn btn-primary">Guardar</button>
                        </div>
                        
                    </form>
                    {{ mensaje }}
                    
                </div>
                <div class="card-footer text-muted"></div>
                
            </div>
        </div>
    </div>
</body>
</html>

{% endblock %}

templates/Producto/registrarProducto.html
{% extends "base1.html" %}

{% load crispy_forms_tags %}

{% block body %}

<!Doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <div class="container py-4">
    <div class="card">
        
        <div class="card-header">
            <b>Crear un Producto</b>
        </div>
        
        <div class="card-body">
            <h4 class="card-title">Datos del Producto</h4>
            <!--False-->
            <form action="" class="formulario_producto" method="POST">
                                
                {% csrf_token %}
                
                {{ form | crispy}}
                    
                <center>
                    <button type="submit" id="btnRegistrar" class="btn btn-primary">Registrar</button>
                </center>
            </form>
        
            
        </div>
        <div class="card-footer text-muted"></div>
        
    </div>
</body>
</html>


    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous">
    </script>
    <!--<script src="/static/js/logic.js"></script>-->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    
      
    
</body>
</html>

{% endblock %}