Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

from ServicioTecnico import views, models
from rest_framework import routers, serializers, viewsets

from django.contrib.auth.models import User

#API Users propia de DJANGO - Problema:Encripta claves
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url','id', 'username', 'password']

class UserViewSet(viewsets.ModelViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()

#API Usuarios
class UsuarioSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = views.Usuario
        fields = ['url','user_id', 'username', 'password']

# ViewSets define the view behavior.
class UsuarioViewSet(viewsets.ModelViewSet):
    queryset = views.Usuario.objects.all()
    serializer_class = UsuarioSerializer

#API Equipo
class EquipoSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = models.Equipo
        fields = ['url','id', 'descripcion', 'marca', 'modelo']

# ViewSets define the view behavior.
class EquipoViewSet(viewsets.ModelViewSet):
    queryset = models.Equipo.objects.all()
    serializer_class = EquipoSerializer

#API RECIBO
class ReciboSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = models.Recibo
        fields = ['url','id', 'fechaEmision', 'valorTotal', 'tipo']

# ViewSets define the view behavior.
class ReciboViewSet(viewsets.ModelViewSet):
    queryset = models.Recibo.objects.all()
    serializer_class = ReciboSerializer


router = routers.DefaultRouter()
router.register(r'User', UserViewSet)
router.register(r'Usuario', UsuarioViewSet)
router.register(r'Equipo', EquipoViewSet)
router.register(r'Recibo', ReciboViewSet)

urlpatterns = [   
    #path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('', include('ServicioTecnico.urls')),
    #path('cliente/', cliente),
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('apiu/', include(router.urls)),
]

ServicioTecnico/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Usuario(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, primary_key=True)
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=30)
    def _str_(self) :
        return str(self.username)

class Cliente(models.Model):
    id = models.AutoField(primary_key = True)
    nombres = models.CharField(max_length = 50, verbose_name = 'Nombres')
    apellidos = models.CharField(max_length = 50, verbose_name = 'Apellidos')
    cedula = models.CharField(max_length = 10, verbose_name = 'Cedula')
    telefono = models.CharField(max_length = 9, verbose_name = 'Telefono')
    telefonoMovil = models.CharField(max_length = 10, verbose_name = 'TelefonoMovil')
    email = models.EmailField()
    direccion = models.CharField(max_length = 100, verbose_name = 'Direccion')

    def nombre_completo(self):
        return "{} {}".format(self.nombres, self.apellidos)
    
    def __str__(self):
        return self.nombre_completo()
    
    def __getitem__(self, key):
        return self.__dict__[key]

class Equipo(models.Model):
    id = models.AutoField(primary_key = True)
    descripcion = models.CharField(max_length = 100, verbose_name = 'Descripción')
    marca = models.CharField(max_length = 50, verbose_name = 'Marca')
    modelo = models.CharField(max_length = 50, verbose_name = 'Modelo')
    numSerie = models.CharField(max_length = 14, verbose_name = 'Numero de Serie')
    observaciones = models.CharField(max_length = 500, verbose_name = 'Observaciones')
    
    def nombre(self):
        return "{} {}".format(self.descripcion, self.marca)
    
    def __str__(self):
        return self.nombre()

class Servicio(models.Model):
    id = models.AutoField(primary_key = True)
    nombre = models.CharField(max_length = 100, verbose_name = 'Nombre')
    descripcion = models.CharField(max_length = 500, verbose_name = 'Descripción')
    valor = models.FloatField(verbose_name = 'Valor')

    def nombre_servicio(self):
        return "{} {}".format(self.nombre, self.valor)
    
    def __str__(self):
        return self.nombre_servicio()

opciones_roles = [
    [0, "Vendedor"],
    [1, "Tecnico"],
    [2, "admin2"]
]

class Empleado(models.Model):
    id = models.AutoField(primary_key = True)
    rol = models.IntegerField(choices=opciones_roles, verbose_name = 'Rol')
    nombres = models.CharField(max_length = 50, verbose_name = 'Nombres')
    apellidos = models.CharField(max_length = 50, verbose_name = 'Apellidos')
    cedula = models.CharField(max_length = 10, verbose_name = 'Cedula')
    email = models.EmailField()
    telefono = models.CharField(max_length = 10, verbose_name = 'Telefono')
    direccion = models.CharField(max_length = 100, verbose_name = 'Direccion')

    def nombre_completo(self):
        return "{} {} {}".format(self.rol, self.nombres, self.apellidos)
    
    def __str__(self):
        return self.nombre_completo()

class Diagnostico(models.Model):
    id = models.AutoField(primary_key = True)
    descripcion = models.CharField(max_length = 500, verbose_name = 'Descripción')
    defecto = models.CharField(max_length = 150, verbose_name = 'Defecto')
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    equipo = models.OneToOneField(Equipo, on_delete=models.CASCADE)

    def nombre_diagnostico(self):
        return "{} {} {}".format(self.equipo, self.defecto, self.descripcion)
    
    def __str__(self):
        return self.nombre_diagnostico()
    
    def __getitem__(self, key):
        return self.__dict__[key]

class Proveedor(models.Model):
    ruc = models.CharField(primary_key = True, max_length = 13)
    nombre = models.CharField(max_length = 50, verbose_name = 'Nombre')
    email = models.EmailField()
    direccion = models.CharField(max_length = 100, verbose_name = 'Direccion')

    def nombre_proveedor(self):
        return "{} {}".format(self.ruc, self.nombre)
    
    def __str__(self):
        return self.nombre_proveedor()

opciones_productos = [
    [0, "Garantia"],
    [1, "Sin Garantia"]
]

class Producto(models.Model):
    id = models.AutoField(primary_key = True)
    nroSerie = models.CharField(max_length = 13, verbose_name = 'Nro Serie')
    nombre = models.CharField(max_length = 50, verbose_name = 'Nombre')
    unidades = models.IntegerField(verbose_name = 'Unidades')
    precioCompra = models.FloatField(verbose_name = 'Precio Compra')
    precioVenta = models.FloatField(verbose_name = 'Precio Venta')
    marca = models.CharField(max_length = 50, verbose_name = 'Marca')
    modelo = models.CharField(max_length = 50, verbose_name = 'Modelo')
    tipo = models.IntegerField(choices=opciones_productos, verbose_name = 'Tipo')
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)

    def nombre_producto(self):
        return "{} {} {} {}".format(self.nroSerie, self.nombre, self.marca, self.tipo)
    
    def __str__(self):
        return self.nombre_producto()

class Pedido(models.Model):
    id = models.AutoField(primary_key = True)
    tiempoEntrega = models.CharField(max_length = 50, verbose_name = 'Tiempo Entrega')
    descripcion = models.CharField(max_length = 500, verbose_name = 'Descripción')
    productos = models.ForeignKey(Producto, on_delete=models.CASCADE)
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.tiempoEntrega

opciones_estadoRecibo = [
    [0, "Creado"],
    [1, "Progreso"],
    [3, "Facturado"]
]

opciones_tipo = [
    [0, "Venta"],
    [1, "Orden de Servicio"],
]

class Recibo(models.Model):
    id = models.AutoField(primary_key = True)
    fechaEmision = models.DateField(verbose_name = 'Fecha de Emisión')
    subTotalProductos = models.FloatField(verbose_name = 'Sub Total de Productos')
    valorTotal = models.FloatField(verbose_name = 'Valor Total')
    fechaCierre = models.DateField(verbose_name = 'Fecha de Cierre')
    estado = models.IntegerField(choices=opciones_estadoRecibo, verbose_name = 'Estado')
    subTotalServicios = models.FloatField(verbose_name = 'Sub Total Servicios')
    tipo = models.IntegerField(choices=opciones_tipo, verbose_name = 'Tipo')
    servicio = models.ManyToManyField(Servicio)
    diagnostico = models.OneToOneField(Diagnostico, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto)

    def nombre_recibo(self):
        return "{} {}".format(self.id, self.fechaEmision)
    
    def __str__(self):
        return self.nombre_recibo()
    
    def __getitem__(self, key):
        return self.__dict__[str, key]

templates/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block tittle %} {% endblock %}</title>
    <link type='text/css' href='{% static "css/style.css" %}' rel='stylesheet'/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <a class="navbar-brand" href="/">
            <img src="{% static 'images/soporte-tecnico.png' %}" alt="" width="30" height="24">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="nav justify-content-start collapse navbar-collapse" id="navbarText">
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a class="nav-link" href="/">Inicio</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle btn-block" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Servicios
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="/Servicios">Todos</a></li>
                        <li><a class="dropdown-item" href="/ServicioMantenimiento">Mantenimiento de computadoras</a></li>
                        <li><a class="dropdown-item" href="/ServicioProgramas">Instalación de programas</a></li>
                        <li><a class="dropdown-item" href="/ServicioAntivirus">Activación de antivirus</a></li>
                        <li><a class="dropdown-item" href="/ServicioSO">Instalación de sistemas operativos</a></li>
                        <li><a class="dropdown-item" href="/ServicioFormateo">Formateo y respaldo de información</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/contactenos/">Contáctenos</a>
                </li>
                
                {% if perms.ServicioTecnico.view_cliente %}
                <li class="nav-item">
                    <a class="nav-link" href="/Cliente">Clientes</a> 
                </li>
                {% endif %}

                {% if perms.ServicioTecnico.view_servicio %}
                <li class="nav-item">
                    <a class="nav-link" href="/Servicio">Servicio</a>
                    
                </li>
                {% endif %}

                {% if perms.ServicioTecnico.view_equipo %}
                <li class="nav-item">
                    {% if user.id == 1 or user.username == 'vendedor' or user.username == 'tecnico' %}
                        <a class="nav-link" href="{% url 'listarEquiposCliente' user.id %}">Equipos</a>
                    {% endif %}
                    {% if user.id != 1 and user.username != 'vendedor' and user.username != 'tecnico' %}
                        <a class="nav-link" href="{% url 'listarEquiposCliente' user.id %}">Mis Cosas</a>
                    {% endif %}
                
                </li>
                {% endif %}

                {% if perms.ServicioTecnico.view_recibo %}
                <li class="nav-item">
                    <a class="nav-link" href="/Recibo">Recibos</a>
                </li>
                {% endif %}

                {% if perms.ServicioTecnico.view_diagnostico %}
                <li class="nav-item">
                    <a class="nav-link" href="/Diagnostico">Diagnostico</a>
                </li>
                {% endif %}

                {% if perms.ServicioTecnico.view_empleado %}
                <li class="nav-item">
                    <a class="nav-link" href="/Empleado">Empleado</a>
                </li>
                {% endif %}

                {% if perms.ServicioTecnico.view_pedido %}
                <li class="nav-item">
                    <a class="nav-link" href="/Pedido">Pedido</a>
                </li>
                {% endif %}

                {% if perms.ServicioTecnico.view_producto %}
                <li class="nav-item">
                    <a class="nav-link" href="/Producto">Producto</a>
                </li>
                {% endif %}

                {% if perms.ServicioTecnico.view_proveedor %}
                <li class="nav-item">
                    <a class="nav-link" href="/Proveedor">Proveedor</a>
                </li>
                {% endif %}
 
            </ul> 
        </div>
        <div class="justify-content-end collapse navbar-collapse" id="navbarText">
            <ul class="nav ">
                {% if request.user.is_authenticated %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Cerrar Sesión</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">{{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        {% for auth in backends.associated %}
                            {% if auth.provider == 'facebook' %}
                                <img src="{{ auth.extra_data.picture.data.url }}" alt="" width="50" height="50">
                            {% endif %}
                        {% endfor %}
                    </li>

                {% else %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Iniciar Sesión</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'registro' %}">Registrate</a>
                    </li>
                    
                {% endif %}
            </ul>
        </div>
    </nav>
    
    {% block body %}

    {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous">
    </script>
    <!--<script src="{% static 'js/logic.js' %}"></script>-->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    
    {% if messages %}
        {% for m in messages %}

            <script>
                Swal.fire({
                    title: 'Felicitaciones',
                    text: '{{m}}',
                    icon: 'success',
                    confirmButtonText: 'Listo',
                    confirmButtonColor: '#007bff'
                })
            </script>
        {% endfor %}
    {% endif %}

    {% block js %}
    {% endblock %}
    
</body>

</html>

templates/contactenos.html
{% extends "./base1.html" %} 

{% load static %}


{% block js %}
  
{% endblock js %}

{% block body %}
<div class="container py-5">
<div class="container">
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button btn btn-sm btn-outline-primary text-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Dirección
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body bg-warning">
        <strong>Bolivar y Sucre</strong>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed btn btn-sm btn-outline-primary text-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Teléfono
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body bg-info">
        <strong>2521293</strong> 
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed btn btn-sm btn-outline-primary text-dark" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Correos electrónicos
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
      <div class="accordion-body bg-success">
        <strong>EmpresaXYZ@gmail.com</strong>
        <br>
        <strong>Boooking@gmail.com</strong>
      </div>
    </div>
  </div>
</div>
</div>
</div>
<div class="container text-center">
    <h3 class="display-6">Nuestras Redes Sociales</h3>
<div class="icon">
    <div class="op icon__facebook">
      <a href="https://www.facebook.com/CajamarcaEstudios"><ion-icon class="fa fa-facebook"></ion-icon></a>
    </div>
    <div class="op icon__twitter">
      <a href="https://twitter.com/"><i class="fa fa-twitter"></i></a>
    </div>
    <div class="op icon__whatsapp">
      <a href="https://www.whatsapp.com/"><ion-icon class="fa fa-whatsapp"></ion-icon></a>
    </div>
    <div class="op icon__linkedin">
      <a href="https://ec.linkedin.com/"><ion-icon class="fa fa-linkedin"></ion-icon></a>
    </div>
    <div class="op icon__instagram">
      <a href="https://www.instagram.com/"><ion-icon class="fa fa-instagram"></ion-icon></a>
    </div>
</div>
</div>

{% endblock %}

templates/home.html
{% extends "./base1.html" %} 

{% load static %}


{% block js %}
  
{% endblock js %}

{% block body %}

<main id="hero">
  <div class="promo">
    <h1></h1>
    <p></p>
  </div>
  <video muted autoplay loop>
    <source src="{% static 'video/SV.mp4' %}"
    type="video/mp4">
  </video>
  <div class="capa"></div>
</main>


{% endblock %}

templates/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}

templates/pdf.html
<style type="text/css">
    body {
        text-align: center;
        margin: 0 auto;
        width: 650px;
        font-family: 'Open Sans', sans-serif;
        background-color: #e2e2e2;
        display: block;
    }

    .text-center {
        text-align: center
    }

    .main-bg-light {
        background-color: #fafafa;
    }

    .title {
        color: #444444;
        font-size: 22px;
        font-weight: bold;
        margin-top: 10px;
        margin-bottom: 10px;
        padding-bottom: 0;
        text-transform: uppercase;
        display: inline-block;
        line-height: 1;
    }

    table {
        margin-top: 30px
    }

    table.top-0 {
        margin-top: 0;
    }

    table.order-detail,
    .order-detail th,
    .order-detail td {
        border: 1px solid #ddd;
        border-collapse: collapse;
    }

</style>
<body>
    <h2>RECIBO TIPO: {{rec.tipo}}</h2>
    <table border="1">
        <thead>
            <th>ID</th>
            <th>Fecha de Emisión</th>
            <th>Sub Total de Productos</th>
            <th>Valor Total</th>
            <th>Fecha de Cierre</th>
            <th>Estado</th>
            <th>Sub Total de Servicios</th>
            <th>Tipo</th>
        </thead>
        <tbody>
            <tr>
                <td>{{ rec.id }}</td>
                <td>{{ rec.fechaEmision }}</td>
                <td>{{ rec.subTotalProductos }}</td>
                <td>{{ rec.valorTotal }}</td>
                <td>{{ rec.fechaCierre }}</td>
                <td>{{ rec.estado }}</td>
                <td>{{ rec.subTotalServicios }}</td>
                <td>{{ rec.tipo }}</td>
            </tr>
            
        </tbody>
    </table>
</body>

templates/registro.html
{% extends 'registro.html' %}

{% block body %}

<form class="form" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" id="submit">Registrarse</button>
</form>

{% endblock %}
